/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.paneles;

import com.luisjuarez.sistemavu.view.SistemaPrincipal;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class Panel_NotaEntrega extends javax.swing.JPanel {

    private Timer timer = new Timer();
    
    /**
     * Creates new form Panel_NotaEntrega
     */
    public Panel_NotaEntrega(Dimension Size) {
        try {
            initComponents();
            SistemaPrincipal.getFacturaService().cargarTabla(TableNotaEntrega);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_NotaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        ContenedorBarraBusqueda = new javax.swing.JPanel();
        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_buscador = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        separador = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ContenedorTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableNotaEntrega = new com.luisjuarez.sistemavu.view.components.CustomTable();
        ContenedorBotones = new javax.swing.JPanel();
        roundedPanel2 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        btn_Anular = new com.luisjuarez.sistemavu.view.components.RoundedButton();

        setLayout(new java.awt.BorderLayout());

        ContenedorBarraBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorBarraBusqueda.setPreferredSize(new java.awt.Dimension(100, 90));
        ContenedorBarraBusqueda.setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(900, 60));
        roundedPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        roundedPanel1.add(jLabel1);

        txt_buscador.setBackground(new java.awt.Color(153, 204, 255));
        txt_buscador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_buscador.setForeground(new java.awt.Color(255, 255, 255));
        txt_buscador.setText("Introduce el id de la nota de entrega");
        txt_buscador.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        txt_buscador.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_buscador.setPreferredSize(new java.awt.Dimension(400, 30));
        txt_buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscadorFocusLost(evt);
            }
        });
        txt_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscadorKeyReleased(evt);
            }
        });
        roundedPanel1.add(txt_buscador);

        btn_buscar.setBackground(new java.awt.Color(0, 0, 102));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("Buscar");
        btn_buscar.setFocusable(false);
        btn_buscar.setPreferredSize(new java.awt.Dimension(90, 32));
        roundedPanel1.add(btn_buscar);

        separador.setOpaque(false);
        separador.setPreferredSize(new java.awt.Dimension(20, 50));
        separador.setRequestFocusEnabled(false);
        roundedPanel1.add(separador);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Nota de Entrega");
        roundedPanel1.add(jLabel2);

        ContenedorBarraBusqueda.add(roundedPanel1, new java.awt.GridBagConstraints());

        add(ContenedorBarraBusqueda, java.awt.BorderLayout.PAGE_START);

        ContenedorTable.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorTable.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(700, 450));

        TableNotaEntrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableNotaEntrega.setPreferredSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setViewportView(TableNotaEntrega);

        ContenedorTable.add(jScrollPane1, new java.awt.GridBagConstraints());

        add(ContenedorTable, java.awt.BorderLayout.CENTER);

        ContenedorBotones.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorBotones.setPreferredSize(new java.awt.Dimension(200, 0));
        ContenedorBotones.setLayout(new java.awt.GridBagLayout());

        roundedPanel2.setBackground(new java.awt.Color(153, 204, 255));
        roundedPanel2.setPreferredSize(new java.awt.Dimension(150, 400));
        roundedPanel2.setRoundBottomLeft(15);
        roundedPanel2.setRoundBottomRight(15);
        roundedPanel2.setRoundTopLeft(15);
        roundedPanel2.setRoundTopRight(15);
        roundedPanel2.setLayout(new java.awt.GridBagLayout());

        btn_Anular.setBackground(new java.awt.Color(0, 0, 102));
        btn_Anular.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Anular.setForeground(new java.awt.Color(255, 255, 255));
        btn_Anular.setText("Anular");
        btn_Anular.setFocusable(false);
        btn_Anular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Anular.setPreferredSize(new java.awt.Dimension(120, 80));
        btn_Anular.setRoundBottomLeft(10);
        btn_Anular.setRoundBottomRight(10);
        btn_Anular.setRoundTopLeft(10);
        btn_Anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnularActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        roundedPanel2.add(btn_Anular, gridBagConstraints);

        ContenedorBotones.add(roundedPanel2, new java.awt.GridBagConstraints());

        add(ContenedorBotones, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorFocusGained
        if (txt_buscador.getText().equalsIgnoreCase("Introduce el id de la nota de entrega")) {
            txt_buscador.setText("");
        }
    }//GEN-LAST:event_txt_buscadorFocusGained

    private void txt_buscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorFocusLost
        if (txt_buscador.getText().isEmpty()) {
            txt_buscador.setText("Introduce el id de la nota de entrega");
        }
    }//GEN-LAST:event_txt_buscadorFocusLost

    private void btn_AnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnularActionPerformed

    private void txt_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorKeyReleased
        timer.cancel(); // Cancelar el temporizador anterior
        timer = new Timer(); // Crear un nuevo temporizador
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    try {
                        if (txt_buscador.getText().isEmpty()) {
                            SistemaPrincipal.getFacturaService().cargarTabla(TableNotaEntrega);
                        }else{
                            SistemaPrincipal.getFacturaService().cargarTabla(TableNotaEntrega, txt_buscador.getText());
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Error al cargar la tabla de Clientes: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                });
            }
        }, 300);
    }//GEN-LAST:event_txt_buscadorKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContenedorBarraBusqueda;
    private javax.swing.JPanel ContenedorBotones;
    private javax.swing.JPanel ContenedorTable;
    private com.luisjuarez.sistemavu.view.components.CustomTable TableNotaEntrega;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Anular;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel2;
    private javax.swing.JPanel separador;
    private javax.swing.JTextField txt_buscador;
    // End of variables declaration//GEN-END:variables
}
