/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.paneles;

import com.luisjuarez.sistemavu.view.SistemaPrincipal;
import java.awt.Dimension;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */

public class Panel_Reportes extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Reportes
     */
    public Panel_Reportes(Dimension Size) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_facturar = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_inventario = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_empleados = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_clientes = new com.luisjuarez.sistemavu.view.components.RoundedButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 550));
        setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 0, 102));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(600, 190));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        roundedPanel1.add(jLabel1, gridBagConstraints);

        btn_facturar.setBackground(new java.awt.Color(153, 204, 255));
        btn_facturar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_facturar.setForeground(new java.awt.Color(0, 0, 0));
        btn_facturar.setText("Ventas");
        btn_facturar.setFocusable(false);
        btn_facturar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_facturar.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_facturar.setRoundBottomLeft(10);
        btn_facturar.setRoundBottomRight(10);
        btn_facturar.setRoundTopLeft(10);
        btn_facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -60;
        gridBagConstraints.ipady = -33;
        roundedPanel1.add(btn_facturar, gridBagConstraints);

        btn_inventario.setBackground(new java.awt.Color(153, 204, 255));
        btn_inventario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_inventario.setForeground(new java.awt.Color(0, 0, 0));
        btn_inventario.setText("Inventario");
        btn_inventario.setFocusable(false);
        btn_inventario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_inventario.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_inventario.setRoundBottomLeft(10);
        btn_inventario.setRoundBottomRight(10);
        btn_inventario.setRoundTopLeft(10);
        btn_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -30;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_inventario, gridBagConstraints);

        btn_empleados.setBackground(new java.awt.Color(153, 204, 255));
        btn_empleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_empleados.setForeground(new java.awt.Color(0, 0, 0));
        btn_empleados.setText("Empleados");
        btn_empleados.setFocusable(false);
        btn_empleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_empleados.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_empleados.setRoundBottomLeft(10);
        btn_empleados.setRoundBottomRight(10);
        btn_empleados.setRoundTopLeft(10);
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_empleados, gridBagConstraints);

        btn_clientes.setBackground(new java.awt.Color(153, 204, 255));
        btn_clientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_clientes.setForeground(new java.awt.Color(0, 0, 0));
        btn_clientes.setText("Clientes");
        btn_clientes.setFocusable(false);
        btn_clientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_clientes.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_clientes.setRoundBottomLeft(10);
        btn_clientes.setRoundBottomRight(10);
        btn_clientes.setRoundTopLeft(10);
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -50;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_clientes, gridBagConstraints);

        add(roundedPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btn_facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturarActionPerformed
            // Crear un JFileChooser
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar archivo PDF");

            // Configurar el JFileChooser para seleccionar archivos (solo para guardar)
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            // Mostrar cuadro de diálogo para guardar archivo
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                // Obtener el archivo seleccionado
                File selectedFile = fileChooser.getSelectedFile();

                // Asegurar que tenga la extensión .pdf
                String filePath = selectedFile.getAbsolutePath();
                if (!filePath.toLowerCase().endsWith(".pdf")) {
                    filePath += ".pdf"; // Agregar extensión si no está incluida
                }

                try {
                    SistemaPrincipal.getFacturaService().reporteFacturasPDF(filePath);
                } catch (SQLException ex) {
                    Logger.getLogger(Panel_Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Archivo guardado en: " + filePath, "Guardado Exitoso!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "El usuario cancelo la operacion","Guardado Fallido!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_facturarActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        // Crear un JFileChooser
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar archivo PDF");

            // Configurar el JFileChooser para seleccionar archivos (solo para guardar)
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            // Mostrar cuadro de diálogo para guardar archivo
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                // Obtener el archivo seleccionado
                File selectedFile = fileChooser.getSelectedFile();

                // Asegurar que tenga la extensión .pdf
                String filePath = selectedFile.getAbsolutePath();
                if (!filePath.toLowerCase().endsWith(".pdf")) {
                    filePath += ".pdf"; // Agregar extensión si no está incluida
                }
                try {
                    SistemaPrincipal.getInventarioService().reporteInventarioPDF(filePath);
                    JOptionPane.showMessageDialog(null, "Archivo guardado en: " + filePath, "Guardado Exitoso!", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(Panel_Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario cancelo la operacion","Guardado Fallido!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_inventarioActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar archivo PDF");

            // Configurar el JFileChooser para seleccionar archivos (solo para guardar)
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            // Mostrar cuadro de diálogo para guardar archivo
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                // Obtener el archivo seleccionado
                File selectedFile = fileChooser.getSelectedFile();

                // Asegurar que tenga la extensión .pdf
                String filePath = selectedFile.getAbsolutePath();
                if (!filePath.toLowerCase().endsWith(".pdf")) {
                    filePath += ".pdf"; // Agregar extensión si no está incluida
                }
                try {
                    SistemaPrincipal.getEmpleadoService().reporteEmpleadosPDF(filePath);
                    JOptionPane.showMessageDialog(null, "Archivo guardado en: " + filePath, "Guardado Exitoso!", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(Panel_Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario cancelo la operacion","Guardado Fallido!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Guardar archivo PDF");

            // Configurar el JFileChooser para seleccionar archivos (solo para guardar)
            fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

            // Mostrar cuadro de diálogo para guardar archivo
            int result = fileChooser.showSaveDialog(null);

            if (result == JFileChooser.APPROVE_OPTION) {
                // Obtener el archivo seleccionado
                File selectedFile = fileChooser.getSelectedFile();

                // Asegurar que tenga la extensión .pdf
                String filePath = selectedFile.getAbsolutePath();
                if (!filePath.toLowerCase().endsWith(".pdf")) {
                    filePath += ".pdf"; // Agregar extensión si no está incluida
                }
                try {
                    SistemaPrincipal.getClienteService().reporteClientesPDF(filePath);
                    JOptionPane.showMessageDialog(null, "Archivo guardado en: " + filePath, "Guardado Exitoso!", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(Panel_Reportes.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El usuario cancelo la operacion","Guardado Fallido!", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btn_clientesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_clientes;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_empleados;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_facturar;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_inventario;
    private javax.swing.JLabel jLabel1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
