/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.paneles;

/**
 *
 * @author Usuario
 */
public class Panel_Reportes extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Reportes
     */
    public Panel_Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Respaldar = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_Restaurar = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_Empleado = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_Clientes = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_Regresar = new com.luisjuarez.sistemavu.view.components.RoundedButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1100, 550));
        setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 0, 102));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(600, 190));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reportes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        roundedPanel1.add(jLabel1, gridBagConstraints);

        btn_Respaldar.setBackground(new java.awt.Color(153, 204, 255));
        btn_Respaldar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Respaldar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Respaldar.setText("Ventas");
        btn_Respaldar.setFocusable(false);
        btn_Respaldar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Respaldar.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_Respaldar.setRoundBottomLeft(10);
        btn_Respaldar.setRoundBottomRight(10);
        btn_Respaldar.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -60;
        gridBagConstraints.ipady = -33;
        roundedPanel1.add(btn_Respaldar, gridBagConstraints);

        btn_Restaurar.setBackground(new java.awt.Color(153, 204, 255));
        btn_Restaurar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Restaurar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Restaurar.setText("Inventario");
        btn_Restaurar.setFocusable(false);
        btn_Restaurar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Restaurar.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_Restaurar.setRoundBottomLeft(10);
        btn_Restaurar.setRoundBottomRight(10);
        btn_Restaurar.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -30;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_Restaurar, gridBagConstraints);

        btn_Empleado.setBackground(new java.awt.Color(153, 204, 255));
        btn_Empleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Empleado.setForeground(new java.awt.Color(255, 255, 255));
        btn_Empleado.setText("Empleados");
        btn_Empleado.setFocusable(false);
        btn_Empleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Empleado.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_Empleado.setRoundBottomLeft(10);
        btn_Empleado.setRoundBottomRight(10);
        btn_Empleado.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -25;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_Empleado, gridBagConstraints);

        btn_Clientes.setBackground(new java.awt.Color(153, 204, 255));
        btn_Clientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        btn_Clientes.setText("Clientes");
        btn_Clientes.setFocusable(false);
        btn_Clientes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Clientes.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_Clientes.setRoundBottomLeft(10);
        btn_Clientes.setRoundBottomRight(10);
        btn_Clientes.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -50;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_Clientes, gridBagConstraints);

        btn_Regresar.setBackground(new java.awt.Color(153, 204, 255));
        btn_Regresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Regresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Regresar.setText("Regresar");
        btn_Regresar.setFocusable(false);
        btn_Regresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Regresar.setPreferredSize(new java.awt.Dimension(140, 80));
        btn_Regresar.setRoundBottomLeft(10);
        btn_Regresar.setRoundBottomRight(10);
        btn_Regresar.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = -50;
        gridBagConstraints.ipady = -33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        roundedPanel1.add(btn_Regresar, gridBagConstraints);

        add(roundedPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Clientes;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Empleado;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Regresar;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Respaldar;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Restaurar;
    private javax.swing.JLabel jLabel1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
