/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.paneles;

import java.awt.Dimension;

/**
 *
 * @author Usuario
 */
public class Panel_Configuracion extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Configuracion
     */
    public Panel_Configuracion(Dimension Size) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        btn_Respaldar = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_Restaurar = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        btn_Empleado = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 550));
        setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 0, 102));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(500, 200));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        btn_Respaldar.setBackground(new java.awt.Color(153, 204, 255));
        btn_Respaldar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Respaldar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Respaldar.setText("Taza del dia");
        btn_Respaldar.setFocusable(false);
        btn_Respaldar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Respaldar.setPreferredSize(new java.awt.Dimension(120, 60));
        btn_Respaldar.setRoundBottomLeft(10);
        btn_Respaldar.setRoundBottomRight(10);
        btn_Respaldar.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        roundedPanel1.add(btn_Respaldar, gridBagConstraints);

        btn_Restaurar.setBackground(new java.awt.Color(153, 204, 255));
        btn_Restaurar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Restaurar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Restaurar.setText("Datos Empresa");
        btn_Restaurar.setFocusable(false);
        btn_Restaurar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Restaurar.setPreferredSize(new java.awt.Dimension(140, 60));
        btn_Restaurar.setRoundBottomLeft(10);
        btn_Restaurar.setRoundBottomRight(10);
        btn_Restaurar.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 30, 10);
        roundedPanel1.add(btn_Restaurar, gridBagConstraints);

        btn_Empleado.setBackground(new java.awt.Color(153, 204, 255));
        btn_Empleado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btn_Empleado.setForeground(new java.awt.Color(255, 255, 255));
        btn_Empleado.setText("Impuestos");
        btn_Empleado.setFocusable(false);
        btn_Empleado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Empleado.setPreferredSize(new java.awt.Dimension(120, 60));
        btn_Empleado.setRoundBottomLeft(10);
        btn_Empleado.setRoundBottomRight(10);
        btn_Empleado.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        roundedPanel1.add(btn_Empleado, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Configuracion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        roundedPanel1.add(jLabel1, gridBagConstraints);

        add(roundedPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Empleado;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Respaldar;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_Restaurar;
    private javax.swing.JLabel jLabel1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
