/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.paneles;

import java.awt.Dimension;

/**
 *
 * @author Usuario
 */
public class Panel_Ayuda extends javax.swing.JPanel {

    /**
     * Creates new form Panel_Ayuda
     */
    public Panel_Ayuda(Dimension Size) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPreguntasFrecuentes = new javax.swing.JTextField();
        roundedButton1 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 550));
        setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 0, 102));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(850, 400));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preguntas Frecuentes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(229, 45));
        roundedPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);

        txtPreguntasFrecuentes.setText("Escribe tu pregunta");
        txtPreguntasFrecuentes.setPreferredSize(new java.awt.Dimension(350, 26));
        txtPreguntasFrecuentes.setRequestFocusEnabled(false);
        jPanel1.add(txtPreguntasFrecuentes);

        roundedButton1.setBackground(new java.awt.Color(153, 204, 255));
        roundedButton1.setText("Buscar");
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        roundedButton1.setPreferredSize(new java.awt.Dimension(80, 30));
        roundedButton1.setRoundTopLeft(10);
        jPanel1.add(roundedButton1);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 300));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        roundedPanel1.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(roundedPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    private javax.swing.JTextField txtPreguntasFrecuentes;
    // End of variables declaration//GEN-END:variables
}
