/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.paneles;

import com.luisjuarez.sistemavu.persistence.AyudaDAO;
import com.luisjuarez.sistemavu.utils.ImagesUtils;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Usuario
 */
public class Panel_Ayuda extends javax.swing.JPanel {
    private AyudaDAO ayudaDAO = new AyudaDAO();
    private Timer timer = new Timer();

    /**
     * Creates new form Panel_Ayuda
     */
    public Panel_Ayuda(Dimension Size) {
        initComponents();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(16);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_buscador = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        lbl_pregunta = new javax.swing.JLabel();
        lbl_imagen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(920, 550));
        setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 0, 102));
        roundedPanel1.setMinimumSize(new java.awt.Dimension(850, 68));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(850, 520));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preguntas Frecuentes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(229, 45));
        roundedPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setOpaque(false);

        txt_buscador.setText("Escribe tu pregunta");
        txt_buscador.setPreferredSize(new java.awt.Dimension(350, 26));
        txt_buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscadorFocusLost(evt);
            }
        });
        txt_buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscadorActionPerformed(evt);
            }
        });
        txt_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscadorKeyReleased(evt);
            }
        });
        jPanel1.add(txt_buscador);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 530));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(880, 10));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 800));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lbl_pregunta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_pregunta.setForeground(new java.awt.Color(0, 0, 0));
        lbl_pregunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_pregunta.setText("Pregunta");
        jPanel3.add(lbl_pregunta, java.awt.BorderLayout.NORTH);

        lbl_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ayuda/Recuperar contraseña.png"))); // NOI18N
        jPanel3.add(lbl_imagen, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        roundedPanel1.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(roundedPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void txt_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorKeyReleased
        timer.cancel(); // Cancelar el temporizador anterior
        timer = new Timer(); // Crear un nuevo temporizador
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    lbl_pregunta.setText(ayudaDAO.buscarAyudasPorTexto(txt_buscador.getText()).getLast().getTitulo());
                    lbl_imagen.setIcon(ImagesUtils.redimensionarIcon(getClass().getResource(ayudaDAO.buscarAyudasPorTexto(txt_buscador.getText()).getLast().getDescripcion()), 900, 2000));
                });
            }
        }, 300); // Retraso de 300ms para evitar búsquedas innecesarias

    }//GEN-LAST:event_txt_buscadorKeyReleased

    private void txt_buscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorFocusGained
        if (txt_buscador.getText().equalsIgnoreCase("Escribe tu pregunta")) {
            txt_buscador.setText("");
        }
    }//GEN-LAST:event_txt_buscadorFocusGained

    private void txt_buscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorFocusLost
        if (txt_buscador.getText().isEmpty()) {
            txt_buscador.setText("Escribe tu pregunta");
        }
    }//GEN-LAST:event_txt_buscadorFocusLost

    private void txt_buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_imagen;
    private javax.swing.JLabel lbl_pregunta;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    private javax.swing.JTextField txt_buscador;
    // End of variables declaration//GEN-END:variables
}
