package com.luisjuarez.sistemavu.view.paneles;

import com.luisjuarez.sistemavu.model.Carrito;
import com.luisjuarez.sistemavu.model.CarritoProducto;
import com.luisjuarez.sistemavu.model.Cliente;
import com.luisjuarez.sistemavu.model.DetalleFactura;
import com.luisjuarez.sistemavu.model.Factura;
import com.luisjuarez.sistemavu.model.Inventario;
import com.luisjuarez.sistemavu.model.Producto;
import com.luisjuarez.sistemavu.view.SistemaPrincipal;
import com.luisjuarez.sistemavu.view.components.Item;
import com.luisjuarez.sistemavu.view.components.ItemInvoice;
import com.luisjuarez.sistemavu.view.formulario.Formulario_Buscar_Cliente;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class Panel_Facturar extends javax.swing.JPanel {

    private Cliente cliente = SistemaPrincipal.getCliente();
    private Carrito carrito = SistemaPrincipal.getCarrito();
    private Timer timer = new Timer();

    /**
     * Creates new form Panel_Facturar
     */
    public Panel_Facturar() {
        initComponents();
        cargarMontoFactura(carrito);
        cargarProductos(SistemaPrincipal.getProductoService().mostrarListaProductos());
        cargarCliente();
        lbl_NotaEntrega.setText(String.valueOf(SistemaPrincipal.getFacturaService().contarFacturas() + 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Articulos = new javax.swing.JPanel();
        Buscador = new javax.swing.JPanel();
        searchBar1 = new com.luisjuarez.sistemavu.view.components.SearchBar();
        Productos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        row_items = new javax.swing.JPanel();
        Factura = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_NotaEntrega = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_cliente_nombre = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_cedula_cliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        items = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_pagar = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        jPanel7 = new javax.swing.JPanel();
        lbl_Exento = new javax.swing.JLabel();
        lbl_exento_dolar = new javax.swing.JLabel();
        Guion = new javax.swing.JLabel();
        lbl_exento_bs = new javax.swing.JLabel();
        lbl_BIG = new javax.swing.JLabel();
        lbl_big_dolar = new javax.swing.JLabel();
        Guionbig = new javax.swing.JLabel();
        lbl_big_bs = new javax.swing.JLabel();
        lbl_Iva = new javax.swing.JLabel();
        lbl_iva_dolar = new javax.swing.JLabel();
        GuionIva = new javax.swing.JLabel();
        lbl_iva_bs = new javax.swing.JLabel();
        lbl_Total = new javax.swing.JLabel();
        lbl_precioTotalapagarDolares = new javax.swing.JLabel();
        GuionTotal = new javax.swing.JLabel();
        lbl_PrecioTotalapagarBolivares = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(920, 550));
        setLayout(new java.awt.BorderLayout());

        Articulos.setBackground(new java.awt.Color(255, 255, 255));
        Articulos.setPreferredSize(new java.awt.Dimension(598, 550));
        Articulos.setLayout(new java.awt.BorderLayout());

        Buscador.setOpaque(false);
        Buscador.setLayout(new java.awt.GridBagLayout());

        searchBar1.setText("ESCRIBE EL NOMBRE O CÓDIGO DEL PRODUCTO A BUSCAR");
        searchBar1.setPreferredSize(new java.awt.Dimension(550, 40));
        searchBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBar1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBar1FocusLost(evt);
            }
        });
        searchBar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchBar1KeyReleased(evt);
            }
        });
        Buscador.add(searchBar1, new java.awt.GridBagConstraints());

        Articulos.add(Buscador, java.awt.BorderLayout.PAGE_START);

        Productos.setOpaque(false);
        Productos.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(550, 400));

        row_items.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout row_itemsLayout = new javax.swing.GroupLayout(row_items);
        row_items.setLayout(row_itemsLayout);
        row_itemsLayout.setHorizontalGroup(
            row_itemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        row_itemsLayout.setVerticalGroup(
            row_itemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(row_items);

        Productos.add(jScrollPane1, new java.awt.GridBagConstraints());

        Articulos.add(Productos, java.awt.BorderLayout.CENTER);

        add(Articulos, java.awt.BorderLayout.CENTER);

        Factura.setBackground(new java.awt.Color(255, 255, 255));
        Factura.setPreferredSize(new java.awt.Dimension(322, 550));
        Factura.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(276, 110));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nota de Entrega:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel2.add(jLabel3, gridBagConstraints);

        lbl_NotaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NotaEntrega.setForeground(new java.awt.Color(255, 255, 255));
        lbl_NotaEntrega.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(lbl_NotaEntrega, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre Cliente:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(-5, 0, 0, 20);
        jPanel2.add(jLabel5, gridBagConstraints);

        lbl_cliente_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cliente_nombre.setText("SIN ASIGNAR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(-5, 0, 0, 0);
        jPanel2.add(lbl_cliente_nombre, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel2.add(jLabel7, gridBagConstraints);

        lbl_cedula_cliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_cedula_cliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cedula_cliente.setText("V-12345678");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel2.add(lbl_cedula_cliente, gridBagConstraints);

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jButton2, gridBagConstraints);

        Factura.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(30, 30, 30));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Artículos Seleccionados");
        jPanel4.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        items.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
        jPanel5Layout.columnWidths = new int[] {272};
        jPanel5Layout.rowHeights = new int[] {70};
        jPanel5Layout.columnWeights = new double[] {0.0};
        jPanel5Layout.rowWeights = new double[] {0.0};
        items.setLayout(jPanel5Layout);
        jScrollPane2.setViewportView(items);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        Factura.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(276, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Monto a pagar");
        jPanel3.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(276, 50));
        jPanel6.setRequestFocusEnabled(false);
        jPanel6.setLayout(new java.awt.GridBagLayout());

        btn_pagar.setBackground(new java.awt.Color(153, 204, 255));
        btn_pagar.setBorder(null);
        btn_pagar.setForeground(new java.awt.Color(30, 30, 30));
        btn_pagar.setText("Cobrar");
        btn_pagar.setEnabled(false);
        btn_pagar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_pagar.setPreferredSize(new java.awt.Dimension(200, 30));
        btn_pagar.setRoundBottomLeft(10);
        btn_pagar.setRoundBottomRight(10);
        btn_pagar.setRoundTopLeft(10);
        btn_pagar.setRoundTopRight(10);
        btn_pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pagarActionPerformed(evt);
            }
        });
        jPanel6.add(btn_pagar, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridBagLayout());

        lbl_Exento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Exento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Exento.setText("EXCENTO:");
        lbl_Exento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel7.add(lbl_Exento, gridBagConstraints);

        lbl_exento_dolar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exento_dolar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exento_dolar.setText("100$");
        jPanel7.add(lbl_exento_dolar, new java.awt.GridBagConstraints());

        Guion.setForeground(new java.awt.Color(255, 255, 255));
        Guion.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel7.add(Guion, gridBagConstraints);

        lbl_exento_bs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_exento_bs.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exento_bs.setText("8000Bs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel7.add(lbl_exento_bs, gridBagConstraints);

        lbl_BIG.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_BIG.setForeground(new java.awt.Color(255, 255, 255));
        lbl_BIG.setText("BIG:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel7.add(lbl_BIG, gridBagConstraints);

        lbl_big_dolar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_big_dolar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_big_dolar.setText("500$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel7.add(lbl_big_dolar, gridBagConstraints);

        Guionbig.setForeground(new java.awt.Color(255, 255, 255));
        Guionbig.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel7.add(Guionbig, gridBagConstraints);

        lbl_big_bs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_big_bs.setForeground(new java.awt.Color(255, 255, 255));
        lbl_big_bs.setText("15000Bs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel7.add(lbl_big_bs, gridBagConstraints);

        lbl_Iva.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Iva.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Iva.setText("IVA 16%:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel7.add(lbl_Iva, gridBagConstraints);

        lbl_iva_dolar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_iva_dolar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_iva_dolar.setText("200$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel7.add(lbl_iva_dolar, gridBagConstraints);

        GuionIva.setForeground(new java.awt.Color(255, 255, 255));
        GuionIva.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel7.add(GuionIva, gridBagConstraints);

        lbl_iva_bs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_iva_bs.setForeground(new java.awt.Color(255, 255, 255));
        lbl_iva_bs.setText("100Bs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel7.add(lbl_iva_bs, gridBagConstraints);

        lbl_Total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Total.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Total.setText("TOTAL:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        jPanel7.add(lbl_Total, gridBagConstraints);

        lbl_precioTotalapagarDolares.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_precioTotalapagarDolares.setForeground(new java.awt.Color(255, 255, 255));
        lbl_precioTotalapagarDolares.setText("400$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel7.add(lbl_precioTotalapagarDolares, gridBagConstraints);

        GuionTotal.setForeground(new java.awt.Color(255, 255, 255));
        GuionTotal.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 5);
        jPanel7.add(GuionTotal, gridBagConstraints);

        lbl_PrecioTotalapagarBolivares.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PrecioTotalapagarBolivares.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PrecioTotalapagarBolivares.setText("3000Bs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel7.add(lbl_PrecioTotalapagarBolivares, gridBagConstraints);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        Factura.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        add(Factura, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_pagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pagarActionPerformed
        try {
            SistemaPrincipal.getFacturaService().registrarFactura(new Factura(
                    0,
                    carrito.calcularBIG() + carrito.calcularExcento(),
                    carrito.calcularIVA(),
                    SistemaPrincipal.getTasa(),
                    carrito.calcularBIG() + carrito.calcularExcento() + carrito.calcularIVA(),
                    carrito.getCantidadTotal(), //cantidad
                    new Timestamp(System.currentTimeMillis()), //fecha
                    SistemaPrincipal.getCliente().getIdCliente(), //cliente
                    SistemaPrincipal.getEmpleado().getIdEmpleado()) //empleado
            );
            try {
                ArrayList<CarritoProducto> listaProductos = carrito.getItems();
                for (CarritoProducto Producto : listaProductos) {
                    DetalleFactura dnt = new DetalleFactura();
                    dnt.setCantidad(Producto.getCantidad());
                    dnt.setPrecioUnitario(Producto.getProducto().getPrecio_venta());
                    dnt.setSubtotal(Producto.getProducto().getPrecio_venta() * Producto.getCantidad());
                    dnt.setFactura_idFactura(Integer.parseInt(lbl_NotaEntrega.getText()));
                    dnt.setProducto_idProducto(Producto.getProducto().getIdProducto());
                    SistemaPrincipal.getDetalleFacturaService().registrarDetalleFactura(dnt);
                    SistemaPrincipal.getInventarioService().disminuirInventario(Producto.getInventario().getIdInventario(), Producto.getCantidad());
                }
                JOptionPane.showMessageDialog(this, "Nota de entrega registrada Exitosamente en la base de datos!", "Registro Exitoso!", JOptionPane.INFORMATION_MESSAGE);
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas guardar la factura en pdf?", "Confirmación", JOptionPane.YES_NO_OPTION);
                if (respuesta == JOptionPane.YES_OPTION) {
                    JFileChooser fileChooser = new JFileChooser();
                    fileChooser.setDialogTitle("Seleccione la ubicación para guardar la factura");
                    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
                    fileChooser.setSelectedFile(new File("factura.pdf"));
                    int userSelection = fileChooser.showSaveDialog(null);
                    if (userSelection == JFileChooser.APPROVE_OPTION) {
                        File archivoSeleccionado = fileChooser.getSelectedFile();
                        try {
                            SistemaPrincipal.detalleFacturaService.generarFacturaPDF(archivoSeleccionado.getAbsolutePath(), Integer.parseInt(lbl_NotaEntrega.getText()));
                            JOptionPane.showMessageDialog(null, "Factura guardada exitosamente en: " + archivoSeleccionado.getAbsolutePath());
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Error al generar la factura: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            e.printStackTrace();
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "El guardado de la factura fue cancelado.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "La factura no será guardada.");
                }
                SistemaPrincipal.setCliente(null);
                cliente = null;
                carrito.limpiarCarrito();
                verificarEstadoBotonPagar();
                cargarProductosFactura(carrito);
                cargarCliente();
                Factura.revalidate();
                Factura.repaint();
            } catch (Exception e) {
                e.printStackTrace(); // Esto te dará más información sobre el problema.
                JOptionPane.showMessageDialog(this, "Error al insertar los detalles!", "Error de registro", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_pagarActionPerformed

    private void searchBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBar1FocusGained
        if (searchBar1.getText().equals("ESCRIBE EL NOMBRE O CÓDIGO DEL PRODUCTO A BUSCAR")) {
            searchBar1.setText("");
        }
    }//GEN-LAST:event_searchBar1FocusGained

    private void searchBar1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBar1FocusLost
        if (searchBar1.getText().equals("")) {
            searchBar1.setText("ESCRIBE EL NOMBRE O CÓDIGO DEL PRODUCTO A BUSCAR");
        }
    }//GEN-LAST:event_searchBar1FocusLost

    private void searchBar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBar1KeyReleased
        timer.cancel(); // Cancelar el temporizador anterior
        timer = new Timer(); // Crear un nuevo temporizador
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                SwingUtilities.invokeLater(() -> {
                    row_items.removeAll();
                    row_items.revalidate();
                    row_items.repaint();
                    cargarProductos(SistemaPrincipal.getProductoService().buscarProductosPorPalabraClave(searchBar1.getText()));
                });
            }
        }, 300);
    }//GEN-LAST:event_searchBar1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Formulario_Buscar_Cliente fbc = new Formulario_Buscar_Cliente(this);
        fbc.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cliente = null;
        SistemaPrincipal.setCliente(cliente);
        cargarCliente();
        verificarEstadoBotonPagar();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Articulos;
    private javax.swing.JPanel Buscador;
    private javax.swing.JPanel Factura;
    private javax.swing.JLabel Guion;
    private javax.swing.JLabel GuionIva;
    private javax.swing.JLabel GuionTotal;
    private javax.swing.JLabel Guionbig;
    private javax.swing.JPanel Productos;
    private com.luisjuarez.sistemavu.view.components.RoundedButton btn_pagar;
    private javax.swing.JPanel items;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_BIG;
    private javax.swing.JLabel lbl_Exento;
    private javax.swing.JLabel lbl_Iva;
    private javax.swing.JLabel lbl_NotaEntrega;
    private javax.swing.JLabel lbl_PrecioTotalapagarBolivares;
    private javax.swing.JLabel lbl_Total;
    private javax.swing.JLabel lbl_big_bs;
    private javax.swing.JLabel lbl_big_dolar;
    private javax.swing.JLabel lbl_cedula_cliente;
    private javax.swing.JLabel lbl_cliente_nombre;
    private javax.swing.JLabel lbl_exento_bs;
    private javax.swing.JLabel lbl_exento_dolar;
    private javax.swing.JLabel lbl_iva_bs;
    private javax.swing.JLabel lbl_iva_dolar;
    private javax.swing.JLabel lbl_precioTotalapagarDolares;
    private javax.swing.JPanel row_items;
    private com.luisjuarez.sistemavu.view.components.SearchBar searchBar1;
    // End of variables declaration//GEN-END:variables

    public void cargarProductosFactura(Carrito carrito) {
        items.removeAll();
        int cant_prod = carrito.getItems().size();
        if (cant_prod < 3) {
            GridLayout gl = new GridLayout(3, 1, 10, 10);
            items.setLayout(gl);
            for (CarritoProducto item : carrito.getItems()) {
                items.add(new ItemInvoice(item.getProducto(), item.getCantidad(), item.getInventario(), this));
                items.revalidate();
                items.repaint();
            }
        } else {
            GridLayout gl = new GridLayout(cant_prod, 1, 10, 10);
            items.setLayout(gl);
            for (CarritoProducto item : carrito.getItems()) {
                items.add(new ItemInvoice(item.getProducto(), item.getCantidad(), item.getInventario(), this));
            }
        }
        items.revalidate();
        items.repaint();
        cargarMontoFactura(carrito);
        verificarEstadoBotonPagar();
    }

    public void verificarEstadoBotonPagar() {
        cliente = SistemaPrincipal.getCliente();
        double monto_total = carrito.calcularBIG() + carrito.calcularExcento() + carrito.calcularIVA();
        if (SistemaPrincipal.getCliente() != null) {
            lbl_cliente_nombre.setText(cliente.getNombre() + (cliente.getApellido() != null ? " " + cliente.getApellido() : ""));
            lbl_cedula_cliente.setText(cliente.getTipo_doc() + ".-" + cliente.getNro_doc());
            if (monto_total > 0 && !lbl_cliente_nombre.getText().equals("SIN ASIGNAR")) {
                btn_pagar.setEnabled(true);
                btn_pagar.setText("Cobrar (" + String.format("%.2f", monto_total) + ") $");
            } else {
                btn_pagar.setText("Cobrar");
                btn_pagar.setEnabled(false);
            }
        } else {
            if (monto_total > 0 && !lbl_cliente_nombre.getText().equals("SIN ASIGNAR")) {
                btn_pagar.setEnabled(true);
                btn_pagar.setText("Cobrar (" + String.format("%.2f", monto_total) + ") $");
                System.out.println("este xd");
            } else {
                btn_pagar.setText("Cobrar");
                btn_pagar.setEnabled(false);
            }
        }
    }

    private void cargarMontoFactura(Carrito carrito) {
        lbl_exento_dolar.setText(String.format(Locale.US, "%.2f", carrito.calcularExcento()) + " $");
        lbl_exento_bs.setText(String.format(Locale.US, "%.2f", carrito.calcularExcento() * SistemaPrincipal.getTasa()) + " Bs");
        lbl_big_dolar.setText(String.format(Locale.US, "%.2f", carrito.calcularBIG()) + " $");
        lbl_big_bs.setText(String.format(Locale.US, "%.2f", carrito.calcularBIG() * SistemaPrincipal.getTasa()) + " Bs");
        lbl_iva_dolar.setText(String.format(Locale.US, "%.2f", carrito.calcularIVA()) + " $");
        lbl_iva_bs.setText(String.format(Locale.US, "%.2f", carrito.calcularIVA()) + " Bs");
        lbl_precioTotalapagarDolares.setText(String.format(Locale.US, "%.2f", carrito.calcularBIG() + carrito.calcularExcento() + carrito.calcularIVA()) + " $");
        lbl_PrecioTotalapagarBolivares.setText(String.format(Locale.US, "%.2f", carrito.calcularBIG() + carrito.calcularExcento() + carrito.calcularIVA() * SistemaPrincipal.getTasa()) + " Bs");
    }

    private void cargarProductos(List<Producto> listaProductos) {
        int cant_prod = listaProductos.size() - 1;
        int row_prod = (cant_prod / 6);
        if (cant_prod <= 17) {
            GridLayout gl = new GridLayout(3, 6, 10, 10);
            row_items.setLayout(gl);
            for (int i = 0; i <= 17; i++) {
                if (i <= cant_prod) {
                    Inventario inventario = SistemaPrincipal.getInventarioService().buscarInventarioPorId(listaProductos.get(i).getIdProducto());
                    if (inventario.getCantidad() > 0) {
                        Item item = new Item(listaProductos.get(i), inventario, carrito, this, items);
                        row_items.add(item);
                    }
                } else {
                    JPanel njp = new JPanel();
                    njp.setOpaque(false);
                    row_items.add(njp);
                }
            }
        } else {
            if (row_prod % 2 != 0) {
                row_prod += 1;
            }
            GridLayout gl = new GridLayout(row_prod, 6, 10, 10);
            row_items.setLayout(gl);
            for (int i = 0; i < cant_prod; i++) {
                Inventario inventario = SistemaPrincipal.getInventarioService().buscarInventarioPorId(listaProductos.get(i).getIdProducto());
                if (inventario.getCantidad() > 0) {
                    row_items.add(new Item(listaProductos.get(i), inventario, carrito, this, items));
                }
            }
        }
    }

    public void cargarCliente() {
        if (cliente != null) {
            lbl_cliente_nombre.setText(cliente.getNombre() + (cliente.getApellido() != null ? " " + cliente.getApellido() : ""));
            lbl_cedula_cliente.setText(cliente.getTipo_doc() + "-" + cliente.getNro_doc());
        } else {
            lbl_cliente_nombre.setText("SIN ASIGNAR");
            lbl_cedula_cliente.setText("V-12345678");
        }
    }
}
