/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.components;

import com.luisjuarez.sistemavu.model.Carrito;
import com.luisjuarez.sistemavu.model.CarritoProducto;
import com.luisjuarez.sistemavu.model.Inventario;
import com.luisjuarez.sistemavu.model.Producto;
import com.luisjuarez.sistemavu.utils.ImagesUtils;
import com.luisjuarez.sistemavu.view.SistemaPrincipal;
import com.luisjuarez.sistemavu.view.paneles.Panel_Facturar;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class ItemInvoice extends javax.swing.JPanel {

    private Carrito carrito = SistemaPrincipal.getCarrito();
    private Producto producto;
    private Inventario inventario;
    private Panel_Facturar panelFacturar;

    /**
     * Creates new form ItemInvoice
     */
    public ItemInvoice(Producto producto, double cantidad, Inventario inventario, Panel_Facturar panelFacturar) {
        initComponents();
        this.producto = producto;
        this.inventario = inventario;
        this.panelFacturar = panelFacturar;
        lbl_Imagen.setIcon(ImagesUtils.redimensionarIcon(getClass().getResource(producto.getImagen_producto()), 70, 70));
        lbl_CantidadProducto.setText(String.valueOf(cantidad));
        lbl_CantidadExistencia.setText(String.valueOf(inventario.getCantidad()));
        jLabel1.setText(producto.getNombre());
        lbl_PrecioDolar.setText(String.format("%.2f", producto.getPrecio_venta()) + " $");
        lbl_PrecioBs.setText(String.format("%.2f", producto.getPrecio_venta() * SistemaPrincipal.getTasa()) + " Bs");
        lbl_TotalDolar.setText(String.format("%.2f", producto.getPrecio_venta() * cantidad) + " $");
        lbl_TotalBs.setText(String.format("%.2f", producto.getPrecio_venta() * cantidad * SistemaPrincipal.getTasa()) + " Bs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel3 = new javax.swing.JLabel();
        lbl_Imagen = new javax.swing.JLabel();
        Descripcion = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_PrecioDolar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_PrecioBs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lbl_CantidadProducto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_CantidadExistencia = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbl_TotalDolar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbl_TotalBs = new javax.swing.JLabel();
        Botones = new javax.swing.JPanel();
        btn_Mas = new javax.swing.JButton();
        btn_Menos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(272, 70));
        setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 102));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(0, 1));
        add(jLabel3, java.awt.BorderLayout.PAGE_START);

        lbl_Imagen.setPreferredSize(new java.awt.Dimension(70, 70));
        add(lbl_Imagen, java.awt.BorderLayout.LINE_START);

        Descripcion.setOpaque(false);
        Descripcion.setLayout(new java.awt.GridLayout(4, 1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre Producto");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        Descripcion.add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Precio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(jLabel2, gridBagConstraints);

        lbl_PrecioDolar.setText("10$");
        jPanel2.add(lbl_PrecioDolar, new java.awt.GridBagConstraints());

        jLabel4.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel2.add(jLabel4, gridBagConstraints);

        lbl_PrecioBs.setText("100Bs");
        jPanel2.add(lbl_PrecioBs, new java.awt.GridBagConstraints());

        Descripcion.add(jPanel2);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Und:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel3.add(jLabel6, gridBagConstraints);

        lbl_CantidadProducto.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel3.add(lbl_CantidadProducto, gridBagConstraints);

        jLabel8.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Exist:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel3.add(jLabel9, gridBagConstraints);

        lbl_CantidadExistencia.setText("5");
        jPanel3.add(lbl_CantidadExistencia, new java.awt.GridBagConstraints());

        Descripcion.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel4.add(jLabel11, gridBagConstraints);

        lbl_TotalDolar.setText("100$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel4.add(lbl_TotalDolar, gridBagConstraints);

        jLabel13.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel4.add(jLabel13, gridBagConstraints);

        lbl_TotalBs.setText("1000Bs");
        jPanel4.add(lbl_TotalBs, new java.awt.GridBagConstraints());

        Descripcion.add(jPanel4);

        add(Descripcion, java.awt.BorderLayout.CENTER);

        Botones.setOpaque(false);
        Botones.setPreferredSize(new java.awt.Dimension(80, 70));
        Botones.setLayout(new java.awt.GridBagLayout());

        btn_Mas.setBackground(new java.awt.Color(0, 0, 102));
        btn_Mas.setForeground(new java.awt.Color(255, 255, 255));
        btn_Mas.setText("-");
        btn_Mas.setPreferredSize(new java.awt.Dimension(30, 30));
        btn_Mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        Botones.add(btn_Mas, gridBagConstraints);

        btn_Menos.setBackground(new java.awt.Color(153, 204, 255));
        btn_Menos.setText("+");
        btn_Menos.setPreferredSize(new java.awt.Dimension(30, 30));
        btn_Menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Botones.add(btn_Menos, gridBagConstraints);

        add(Botones, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MasActionPerformed

        int cantidad = Integer.parseInt(JOptionPane.showInputDialog(null, "Seleccione la cantidad de productos a aumentar:"));

// Validar que la cantidad sea positiva y menor o igual al inventario
        if (cantidad > 0 && cantidad <= inventario.getCantidad()) {
            carrito.agregarProducto(producto, inventario, cantidad);
            panelFacturar.cargarProductosFactura(carrito);
        } else {
            JOptionPane.showMessageDialog(null, "La cantidad ingresada no es válida. Asegúrese de que sea un valor positivo y no exceda el inventario disponible.");
        }

    }//GEN-LAST:event_btn_MasActionPerformed

    private void btn_MenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenosActionPerformed

        try {
            String input = JOptionPane.showInputDialog(null, "Seleccione la cantidad de productos a disminuir:");
            if (input == null || input.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "No se ingresó ninguna cantidad.");
                return;
            }

            int cantidad = Integer.parseInt(input);

            for (CarritoProducto item : carrito.getItems()) {
                if (item.getProducto().getCodigo().equals(producto.getCodigo())) {
                    if (cantidad > 0 && cantidad <= item.getCantidad()) {
                        carrito.disminuirProducto(producto, item.getInventario(), cantidad);
                        panelFacturar.cargarProductosFactura(carrito);
                        return;
                    } else {
                        JOptionPane.showMessageDialog(null, "La cantidad ingresada no es válida. Asegúrese de que sea un valor positivo y no exceda la cantidad en el carrito.");
                        return;
                    }
                }
            }

            JOptionPane.showMessageDialog(null, "El producto no existe en el carrito.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Entrada no válida. Por favor, ingrese un número entero positivo.");
        }


    }//GEN-LAST:event_btn_MenosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JPanel Descripcion;
    private javax.swing.JButton btn_Mas;
    private javax.swing.JButton btn_Menos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_CantidadExistencia;
    private javax.swing.JLabel lbl_CantidadProducto;
    private javax.swing.JLabel lbl_Imagen;
    private javax.swing.JLabel lbl_PrecioBs;
    private javax.swing.JLabel lbl_PrecioDolar;
    private javax.swing.JLabel lbl_TotalBs;
    private javax.swing.JLabel lbl_TotalDolar;
    // End of variables declaration//GEN-END:variables
}
