/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.components;

import com.luisjuarez.sistemavu.model.Carrito;
import com.luisjuarez.sistemavu.model.Inventario;
import com.luisjuarez.sistemavu.model.Producto;
import com.luisjuarez.sistemavu.utils.ImagesUtils;
import com.luisjuarez.sistemavu.view.SistemaPrincipal;
import com.luisjuarez.sistemavu.view.paneles.Panel_Facturar;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class Item extends javax.swing.JPanel {
    private Producto producto;
    private Inventario inventario;
    private Carrito carrito;
    private JPanel panel;
    private Panel_Facturar panelFacturar; 
    
    /**
     * Creates new form Item
     */
    public Item(Producto producto, Inventario inventario, Carrito carrito, Panel_Facturar panelFacturar, JPanel panel) {
        initComponents();
        this.producto = producto;
        this.inventario = inventario;
        this.carrito = carrito;
        this.panelFacturar = panelFacturar;
        this.panel = panel;
        jLabel1.setIcon(ImagesUtils.redimensionarIcon(getClass().getResource(producto.getImagen_producto()), 150, 150));
        lbl_NombreProducto.setText(producto.getNombre());
        lbl_PrecioProductoBs.setText(String.format("%.2f",producto.getPrecio_venta()*SistemaPrincipal.getTasa())+" Bs");
        lbl_PrecioProductoDolar.setText(String.format("%.2f", producto.getPrecio_venta())+" $");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roundedButton1 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_NombreProducto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_PrecioProductoDolar = new javax.swing.JLabel();
        lbl_Guion = new javax.swing.JLabel();
        lbl_PrecioProductoBs = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(130, 220));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(37, 130));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        roundedButton1.setBackground(new java.awt.Color(0, 0, 102));
        roundedButton1.setBorder(null);
        roundedButton1.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton1.setText("Agregar");
        roundedButton1.setFocusable(false);
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roundedButton1.setPreferredSize(new java.awt.Dimension(115, 30));
        roundedButton1.setRoundBottomLeft(10);
        roundedButton1.setRoundBottomRight(10);
        roundedButton1.setRoundTopLeft(10);
        roundedButton1.setRoundTopRight(10);
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(roundedButton1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbl_NombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NombreProducto.setText("Nombre Producto");
        lbl_NombreProducto.setPreferredSize(new java.awt.Dimension(37, 20));
        jPanel2.add(lbl_NombreProducto, java.awt.BorderLayout.NORTH);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        lbl_PrecioProductoDolar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PrecioProductoDolar.setText("200$");
        jPanel3.add(lbl_PrecioProductoDolar, new java.awt.GridBagConstraints());

        lbl_Guion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Guion.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(lbl_Guion, gridBagConstraints);

        lbl_PrecioProductoBs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PrecioProductoBs.setText("100bs");
        jPanel3.add(lbl_PrecioProductoBs, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        carrito.agregarProducto(producto, inventario, 1);
        panelFacturar.cargarProductosFactura(carrito);
    }//GEN-LAST:event_roundedButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Guion;
    private javax.swing.JLabel lbl_NombreProducto;
    private javax.swing.JLabel lbl_PrecioProductoBs;
    private javax.swing.JLabel lbl_PrecioProductoDolar;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton1;
    // End of variables declaration//GEN-END:variables
}
