/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view.components;

/**
 *
 * @author Usuario
 */
public class Item extends javax.swing.JPanel {

    /**
     * Creates new form Item
     */
    public Item() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        roundedButton1 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_NombreProducto = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_PrecioProductoDolar = new javax.swing.JLabel();
        lbl_Guion = new javax.swing.JLabel();
        lbl_PrecioProductoBs = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(130, 220));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(37, 130));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(60, 40));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        roundedButton1.setBackground(new java.awt.Color(0, 0, 102));
        roundedButton1.setBorder(null);
        roundedButton1.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton1.setText("Agregar");
        roundedButton1.setFocusable(false);
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        roundedButton1.setPreferredSize(new java.awt.Dimension(115, 30));
        roundedButton1.setRoundBottomLeft(10);
        roundedButton1.setRoundBottomRight(10);
        roundedButton1.setRoundTopLeft(10);
        roundedButton1.setRoundTopRight(10);
        jPanel1.add(roundedButton1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(130, 50));
        jPanel2.setLayout(new java.awt.BorderLayout());

        lbl_NombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_NombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_NombreProducto.setText("Nombre Producto");
        lbl_NombreProducto.setPreferredSize(new java.awt.Dimension(37, 20));
        jPanel2.add(lbl_NombreProducto, java.awt.BorderLayout.NORTH);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        lbl_PrecioProductoDolar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PrecioProductoDolar.setText("200$");
        jPanel3.add(lbl_PrecioProductoDolar, new java.awt.GridBagConstraints());

        lbl_Guion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_Guion.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel3.add(lbl_Guion, gridBagConstraints);

        lbl_PrecioProductoBs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_PrecioProductoBs.setText("100bs");
        jPanel3.add(lbl_PrecioProductoBs, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Guion;
    private javax.swing.JLabel lbl_NombreProducto;
    private javax.swing.JLabel lbl_PrecioProductoBs;
    private javax.swing.JLabel lbl_PrecioProductoDolar;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton1;
    // End of variables declaration//GEN-END:variables
}
