/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.luisjuarez.sistemavu.view;

/**
 *
 * @author conta
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        roundedButton1 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton2 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton3 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton4 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton9 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton5 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton6 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton7 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton10 = new com.luisjuarez.sistemavu.view.components.RoundedButton();
        roundedButton8 = new com.luisjuarez.sistemavu.view.components.RoundedButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1024, 550));
        setLayout(new java.awt.GridBagLayout());

        roundedButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/member-list.png"))); // NOI18N
        roundedButton1.setText("Cliente");
        roundedButton1.setFocusPainted(false);
        roundedButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton1.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton1.setRoundBottomLeft(10);
        roundedButton1.setRoundBottomRight(10);
        roundedButton1.setRoundTopLeft(10);
        roundedButton1.setRoundTopRight(10);
        roundedButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton1, gridBagConstraints);

        roundedButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-invoice-dollar.png"))); // NOI18N
        roundedButton2.setText("Facturar");
        roundedButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton2.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton2.setRoundBottomLeft(10);
        roundedButton2.setRoundBottomRight(10);
        roundedButton2.setRoundTopLeft(10);
        roundedButton2.setRoundTopRight(10);
        roundedButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton2, gridBagConstraints);

        roundedButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/supplier-alt.png"))); // NOI18N
        roundedButton3.setText("Inventario");
        roundedButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton3.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton3.setRoundBottomLeft(10);
        roundedButton3.setRoundBottomRight(10);
        roundedButton3.setRoundTopLeft(10);
        roundedButton3.setRoundTopRight(10);
        roundedButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton3, gridBagConstraints);

        roundedButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/truck-box.png"))); // NOI18N
        roundedButton4.setText("Proveedor");
        roundedButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton4.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton4.setRoundBottomLeft(10);
        roundedButton4.setRoundBottomRight(10);
        roundedButton4.setRoundTopLeft(10);
        roundedButton4.setRoundTopRight(10);
        roundedButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton4, gridBagConstraints);

        roundedButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analytics.png"))); // NOI18N
        roundedButton9.setText("Reportes");
        roundedButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton9.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton9.setRoundBottomLeft(10);
        roundedButton9.setRoundBottomRight(10);
        roundedButton9.setRoundTopLeft(10);
        roundedButton9.setRoundTopRight(10);
        roundedButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton9, gridBagConstraints);

        roundedButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/box-open-full.png"))); // NOI18N
        roundedButton5.setText("Producto");
        roundedButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton5.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton5.setRoundBottomLeft(10);
        roundedButton5.setRoundBottomRight(10);
        roundedButton5.setRoundTopLeft(10);
        roundedButton5.setRoundTopRight(10);
        roundedButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton5, gridBagConstraints);

        roundedButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/employee-man-alt.png"))); // NOI18N
        roundedButton6.setText("Empleados");
        roundedButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton6.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton6.setRoundBottomLeft(10);
        roundedButton6.setRoundBottomRight(10);
        roundedButton6.setRoundTopLeft(10);
        roundedButton6.setRoundTopRight(10);
        roundedButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton6, gridBagConstraints);

        roundedButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/marketplace-alt.png"))); // NOI18N
        roundedButton7.setText("Compras");
        roundedButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton7.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton7.setRoundBottomLeft(10);
        roundedButton7.setRoundBottomRight(10);
        roundedButton7.setRoundTopLeft(10);
        roundedButton7.setRoundTopRight(10);
        roundedButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton7, gridBagConstraints);

        roundedButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/interrogation.png"))); // NOI18N
        roundedButton10.setText("Ayuda");
        roundedButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton10.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton10.setRoundBottomLeft(10);
        roundedButton10.setRoundBottomRight(10);
        roundedButton10.setRoundTopLeft(10);
        roundedButton10.setRoundTopRight(10);
        roundedButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton10, gridBagConstraints);

        roundedButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/it.png"))); // NOI18N
        roundedButton8.setText("Configuración");
        roundedButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        roundedButton8.setPreferredSize(new java.awt.Dimension(120, 120));
        roundedButton8.setRoundBottomLeft(10);
        roundedButton8.setRoundBottomRight(10);
        roundedButton8.setRoundTopLeft(10);
        roundedButton8.setRoundTopRight(10);
        roundedButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(roundedButton8, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton1;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton10;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton2;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton3;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton4;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton5;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton6;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton7;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton8;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton9;
    // End of variables declaration//GEN-END:variables
}
