/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luisjuarez.sistemavu.view;

import com.luisjuarez.sistemavu.model.Empleado;
import com.luisjuarez.sistemavu.persistence.TokenManager;
import com.luisjuarez.sistemavu.view.formulario.FormularioRecuperarContrasena;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public RecuperarContraseña() {

        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        lbl_author = new javax.swing.JLabel();
        lbl_copyright = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        btn_close = new javax.swing.JButton();
        lbl_userImg = new javax.swing.JLabel();
        lbl_RecuperarContraseña = new javax.swing.JLabel();
        txt_correoContraseña = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();
        btn_iniciarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        header.setBackground(new java.awt.Color(0, 0, 255));
        header.setForeground(new java.awt.Color(51, 51, 51));
        header.setPreferredSize(new java.awt.Dimension(300, 400));
        header.setLayout(new java.awt.GridBagLayout());

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        header.add(lbl_logo, gridBagConstraints);

        lbl_title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("SistemaVU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        header.add(lbl_title, gridBagConstraints);

        lbl_author.setForeground(new java.awt.Color(255, 255, 255));
        lbl_author.setText("SistemaVU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        header.add(lbl_author, gridBagConstraints);

        lbl_copyright.setForeground(new java.awt.Color(255, 255, 255));
        lbl_copyright.setText("Todos los derechos reservados © 2024");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        header.add(lbl_copyright, gridBagConstraints);

        getContentPane().add(header, java.awt.BorderLayout.WEST);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setForeground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(300, 400));
        body.setLayout(new java.awt.GridBagLayout());

        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        btn_close.setBorder(null);
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        body.add(btn_close, gridBagConstraints);

        lbl_userImg.setBackground(new java.awt.Color(255, 255, 255));
        lbl_userImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lock.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 30, 10, 0);
        body.add(lbl_userImg, gridBagConstraints);

        lbl_RecuperarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_RecuperarContraseña.setForeground(new java.awt.Color(69, 69, 69));
        lbl_RecuperarContraseña.setText("Recuperacion de Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 30, 0);
        body.add(lbl_RecuperarContraseña, gridBagConstraints);

        txt_correoContraseña.setBackground(new java.awt.Color(69, 69, 69));
        txt_correoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        txt_correoContraseña.setText("Ingrese su correo");
        txt_correoContraseña.setMargin(new java.awt.Insets(2, 10, 2, 6));
        txt_correoContraseña.setMinimumSize(new java.awt.Dimension(180, 26));
        txt_correoContraseña.setPreferredSize(new java.awt.Dimension(180, 26));
        txt_correoContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_correoContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_correoContraseñaFocusLost(evt);
            }
        });
        txt_correoContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_correoContraseñaKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 0);
        body.add(txt_correoContraseña, gridBagConstraints);

        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        btn_enviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btn_enviarKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 15, 0);
        body.add(btn_enviar, gridBagConstraints);

        lbl_error.setForeground(new java.awt.Color(255, 255, 255));
        lbl_error.setText("Usuario o contraseña incorecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 15, 0);
        body.add(lbl_error, gridBagConstraints);

        btn_iniciarSesion.setBackground(new java.awt.Color(69, 69, 69));
        btn_iniciarSesion.setForeground(new java.awt.Color(69, 69, 69));
        btn_iniciarSesion.setText("Iniciar Sesion");
        btn_iniciarSesion.setBorder(null);
        btn_iniciarSesion.setBorderPainted(false);
        btn_iniciarSesion.setContentAreaFilled(false);
        btn_iniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 40, 0);
        body.add(btn_iniciarSesion, gridBagConstraints);

        getContentPane().add(body, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_correoContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_correoContraseñaFocusGained
        if (txt_correoContraseña.getText().equalsIgnoreCase("Ingrese su correo")) {
            txt_correoContraseña.setText("");
        }
    }//GEN-LAST:event_txt_correoContraseñaFocusGained

    private void txt_correoContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_correoContraseñaFocusLost
        if (txt_correoContraseña.getText().isEmpty()) {
            txt_correoContraseña.setText("Ingrese su correo");
        }
    }//GEN-LAST:event_txt_correoContraseñaFocusLost

    private void txt_correoContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoContraseñaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String email = txt_correoContraseña.getText();
            Empleado empleado = SistemaPrincipal.getEmpleadoService().buscarEmpleadoPorCorreo(email);
            if (empleado != null) {
                String token = TokenManager.generateToken();

                // Guardar el token
                TokenManager.saveToken(email, token);

                // Enviar el token por correo
                TokenManager.sendEmail(email, "Recupera tu contraseña", "Tu usuario es: " + empleado.getUsuario() + "\nTu token de recuperación es: " + token);

                // Validar el token (prueba con el token recibido por correo)
                String tokenString = JOptionPane.showInputDialog("Digite el token");
                boolean isValid = TokenManager.validateToken(email, tokenString);
                if (isValid) {
                    Login lg = new Login();
                    lg.setVisible(true);
                    FormularioRecuperarContrasena frc = new FormularioRecuperarContrasena(empleado.getIdEmpleado());
                    frc.setVisible(true);
                    this.dispose();
                } else {
                    System.out.println("Token inválido o expirado.");
                }

                // Eliminar el token tras su uso
                TokenManager.deleteToken(token);
            } else {
                JOptionPane.showMessageDialog(null,
                        "El correo electrónico no está registrado en nuestra base de datos. Por favor, verifica e inténtalo nuebamente.",
                        "Correo no registrado",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_correoContraseñaKeyPressed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        String email = txt_correoContraseña.getText();
        Empleado empleado = SistemaPrincipal.getEmpleadoService().buscarEmpleadoPorCorreo(email);
        if (empleado != null) {
            String token = TokenManager.generateToken();

            // Guardar el token
            TokenManager.saveToken(email, token);

            // Enviar el token por correo
            TokenManager.sendEmail(email, "Recupera tu contraseña", "Tu usuario es: " + empleado.getUsuario() + "\nTu token de recuperación es: " + token);

            // Validar el token (prueba con el token recibido por correo)
            String tokenString = JOptionPane.showInputDialog("Digite el token");
            boolean isValid = TokenManager.validateToken(email, tokenString);
            if (isValid) {
                Login lg = new Login();
                lg.setVisible(true);
                FormularioRecuperarContrasena frc = new FormularioRecuperarContrasena(empleado.getIdEmpleado());
                frc.setVisible(true);
                this.dispose();
            } else {
                System.out.println("Token inválido o expirado.");
            }

            // Eliminar el token tras su uso
            TokenManager.deleteToken(token);
        } else {
            JOptionPane.showMessageDialog(null,
                    "El correo electrónico no está registrado en nuestra base de datos. Por favor, verifica e inténtalo nuevamente.",
                    "Correo no registrado",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_enviarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_enviarKeyPressed

    }//GEN-LAST:event_btn_enviarKeyPressed

    private void btn_iniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarSesionActionPerformed
        this.dispose();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_btn_iniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_iniciarSesion;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lbl_RecuperarContraseña;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JLabel lbl_userImg;
    private javax.swing.JTextField txt_correoContraseña;
    // End of variables declaration//GEN-END:variables
}
