package com.luisjuarez.sistemavu.view;

import com.luisjuarez.sistemavu.model.Empleado;
import com.luisjuarez.sistemavu.persistence.impl.CategoriaDAOImplMariaDB;
import com.luisjuarez.sistemavu.persistence.impl.ClienteDAOImplMariaDB;
import com.luisjuarez.sistemavu.persistence.impl.CompraDAOImplMariaDB;
import com.luisjuarez.sistemavu.persistence.impl.EmpleadoDAOImplMariaDB;
import com.luisjuarez.sistemavu.persistence.impl.InventarioDAOImplMariaDB;
import com.luisjuarez.sistemavu.persistence.impl.ProductoDAOImplMariaDB;
import com.luisjuarez.sistemavu.persistence.impl.ProveedorDAOImplMariaDB;
import com.luisjuarez.sistemavu.service.CategoriaService;
import com.luisjuarez.sistemavu.service.ClienteService;
import com.luisjuarez.sistemavu.service.CompraService;
import com.luisjuarez.sistemavu.service.EmpleadoService;
import com.luisjuarez.sistemavu.service.InventarioService;
import com.luisjuarez.sistemavu.service.ProductoService;
import com.luisjuarez.sistemavu.service.ProveedorService;
import com.luisjuarez.sistemavu.service.impl.CategoriaServiceImpl;
import com.luisjuarez.sistemavu.service.impl.ClienteServiceImpl;
import com.luisjuarez.sistemavu.service.impl.CompraServiceImpl;
import com.luisjuarez.sistemavu.service.impl.EmpleadoServiceImpl;
import com.luisjuarez.sistemavu.service.impl.InventarioServiceImpl;
import com.luisjuarez.sistemavu.service.impl.ProductoServiceImpl;
import com.luisjuarez.sistemavu.service.impl.ProveedorServiceImpl;

/**
 *
 * @author conta
 */
public class SistemaPrincipal extends javax.swing.JFrame {

    private static Empleado empleado = new Empleado(1, "Juan", "Pérez", "juan.perez@example.com", "juanperez", "contraseñaSegura123");
    public static InventarioService inventarioService = new InventarioServiceImpl(new InventarioDAOImplMariaDB());
    public static ClienteService clienteService = new ClienteServiceImpl(new ClienteDAOImplMariaDB());
    public static ProductoService productoService = new ProductoServiceImpl(new ProductoDAOImplMariaDB());
    public static ProveedorService proveedorService = new ProveedorServiceImpl(new ProveedorDAOImplMariaDB());
    public static CategoriaService categoriaService = new CategoriaServiceImpl(new CategoriaDAOImplMariaDB());
    public static EmpleadoService empleadoService = new EmpleadoServiceImpl(new EmpleadoDAOImplMariaDB());
    public static CompraService compraService = new CompraServiceImpl(new CompraDAOImplMariaDB());
    
    public static Empleado getEmpleado() {
        return empleado;
    }

    public static void setEmpleado(Empleado empleado) {
        SistemaPrincipal.empleado = empleado;
    }

    public static ClienteService getClienteService() {
        return clienteService;
    }

    public static void setClienteService(ClienteService clienteService) {
        SistemaPrincipal.clienteService = clienteService;
    }

    public static ProductoService getProductoService() {
        return productoService;
    }

    public static void setProductoService(ProductoService productoService) {
        SistemaPrincipal.productoService = productoService;
    }

    public static ProveedorService getProveedorService() {
        return proveedorService;
    }

    public static void setProveedorService(ProveedorService proveedorService) {
        SistemaPrincipal.proveedorService = proveedorService;
    }

    public static CategoriaService getCategoriaService() {
        return categoriaService;
    }

    public static void setCategoriaService(CategoriaService categoriaService) {
        SistemaPrincipal.categoriaService = categoriaService;
    }

    public static InventarioService getInventarioService() {
        return inventarioService;
    }

    public static void setInventarioService(InventarioService inventarioService) {
        SistemaPrincipal.inventarioService = inventarioService;
    }

    public static EmpleadoService getEmpleadoService() {
        return empleadoService;
    }

    public static void setEmpleadoService(EmpleadoService empleadoService) {
        SistemaPrincipal.empleadoService = empleadoService;
    }

    public static CompraService getCompraService() {
        return compraService;
    }

    public static void setCompraService(CompraService compraService) {
        SistemaPrincipal.compraService = compraService;
    }
    
    /**
     * Creates new form SistemaVU
     */
    public SistemaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        body = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setBackground(new java.awt.Color(86, 86, 86));
        header.setPreferredSize(new java.awt.Dimension(0, 50));
        header.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 7));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apps.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apps_hover.png"))); // NOI18N
        jPanel1.add(jButton1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SistemaVU - ");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADMIN");
        jPanel1.add(jLabel2);

        header.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 7));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-out-alt.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-out-alt-hover.png"))); // NOI18N
        jPanel2.add(jButton2);

        header.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(header, java.awt.BorderLayout.NORTH);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setPreferredSize(new java.awt.Dimension(1024, 550));
        body.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
