/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luisjuarez.sistemavu.view.formulario;

/**
 *
 * @author Usuario
 */
public class Formulario_Permisos extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_Permisos
     */
    public Formulario_Permisos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Corpus = new javax.swing.JPanel();
        Facturar = new javax.swing.JCheckBox();
        Cliente = new javax.swing.JCheckBox();
        Proveedor = new javax.swing.JCheckBox();
        Categoria = new javax.swing.JCheckBox();
        Producto = new javax.swing.JCheckBox();
        Inventario = new javax.swing.JCheckBox();
        NotadeEntrega = new javax.swing.JCheckBox();
        Mantenimiento = new javax.swing.JCheckBox();
        Reporte = new javax.swing.JCheckBox();
        Configuracion = new javax.swing.JCheckBox();
        Footer = new javax.swing.JPanel();
        roundedButton1 = new com.luisjuarez.sistemavu.view.components.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setPreferredSize(new java.awt.Dimension(508, 581));
        setResizable(false);

        Header.setBackground(new java.awt.Color(0, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(100, 100));
        Header.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 30, 30));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Permisos de Empleado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        Header.add(jLabel2, gridBagConstraints);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Corpus.setBackground(new java.awt.Color(0, 255, 255));
        Corpus.setPreferredSize(new java.awt.Dimension(508, 0));
        Corpus.setLayout(new java.awt.GridBagLayout());

        Facturar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Facturar.setForeground(new java.awt.Color(30, 30, 30));
        Facturar.setText("Facturar");
        Facturar.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        Corpus.add(Facturar, gridBagConstraints);

        Cliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Cliente.setForeground(new java.awt.Color(30, 30, 30));
        Cliente.setText("Clientes");
        Cliente.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        Corpus.add(Cliente, gridBagConstraints);

        Proveedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Proveedor.setForeground(new java.awt.Color(30, 30, 30));
        Proveedor.setText("Proveedor");
        Proveedor.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        Corpus.add(Proveedor, gridBagConstraints);

        Categoria.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Categoria.setForeground(new java.awt.Color(30, 30, 30));
        Categoria.setText("Categoría");
        Categoria.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        Corpus.add(Categoria, gridBagConstraints);

        Producto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Producto.setForeground(new java.awt.Color(30, 30, 30));
        Producto.setText("Producto");
        Producto.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        Corpus.add(Producto, gridBagConstraints);

        Inventario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Inventario.setForeground(new java.awt.Color(30, 30, 30));
        Inventario.setText("Inventario");
        Inventario.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 0);
        Corpus.add(Inventario, gridBagConstraints);

        NotadeEntrega.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        NotadeEntrega.setForeground(new java.awt.Color(30, 30, 30));
        NotadeEntrega.setText("Nota de Entrega");
        NotadeEntrega.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 0);
        Corpus.add(NotadeEntrega, gridBagConstraints);

        Mantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Mantenimiento.setForeground(new java.awt.Color(30, 30, 30));
        Mantenimiento.setText("Mantenimiento");
        Mantenimiento.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 0);
        Corpus.add(Mantenimiento, gridBagConstraints);

        Reporte.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Reporte.setForeground(new java.awt.Color(30, 30, 30));
        Reporte.setText("Reportes");
        Reporte.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 0);
        Corpus.add(Reporte, gridBagConstraints);

        Configuracion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Configuracion.setForeground(new java.awt.Color(30, 30, 30));
        Configuracion.setText("Configuración");
        Configuracion.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 20, 0);
        Corpus.add(Configuracion, gridBagConstraints);

        getContentPane().add(Corpus, java.awt.BorderLayout.CENTER);

        Footer.setBackground(new java.awt.Color(0, 255, 255));
        Footer.setMinimumSize(new java.awt.Dimension(0, 39));
        Footer.setPreferredSize(new java.awt.Dimension(250, 100));
        Footer.setLayout(new java.awt.GridBagLayout());

        roundedButton1.setBackground(new java.awt.Color(0, 0, 102));
        roundedButton1.setForeground(new java.awt.Color(255, 255, 255));
        roundedButton1.setText("Guardar");
        roundedButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        roundedButton1.setPreferredSize(new java.awt.Dimension(250, 50));
        roundedButton1.setRoundTopLeft(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        Footer.add(roundedButton1, gridBagConstraints);

        getContentPane().add(Footer, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Categoria;
    private javax.swing.JCheckBox Cliente;
    private javax.swing.JCheckBox Configuracion;
    private javax.swing.JPanel Corpus;
    private javax.swing.JCheckBox Facturar;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header;
    private javax.swing.JCheckBox Inventario;
    private javax.swing.JCheckBox Mantenimiento;
    private javax.swing.JCheckBox NotadeEntrega;
    private javax.swing.JCheckBox Producto;
    private javax.swing.JCheckBox Proveedor;
    private javax.swing.JCheckBox Reporte;
    private javax.swing.JLabel jLabel2;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton1;
    // End of variables declaration//GEN-END:variables
}
