/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.luisjuarez.sistemavu.view.formulario;

import com.luisjuarez.sistemavu.model.DetalleCompra;
import com.luisjuarez.sistemavu.model.Factura;
import com.luisjuarez.sistemavu.view.SistemaPrincipal;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FormularioVerDetalles extends javax.swing.JFrame {

    private Factura factura;

    /**
     * Creates new form FormularioVerDetalles
     */
    public FormularioVerDetalles(Factura factura) {
        try {
            initComponents();
            this.factura = factura;
            SistemaPrincipal.getDetalleFacturaService().cargarTabla(TableDetalleNotaEntrega, factura.getIdFactura());
            this.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(FormularioVerDetalles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        top = new javax.swing.JPanel();
        roundedPanel1 = new com.luisjuarez.sistemavu.view.components.RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDetalleNotaEntrega = new com.luisjuarez.sistemavu.view.components.CustomTable();
        buttom = new javax.swing.JPanel();
        roundedButton1 = new com.luisjuarez.sistemavu.view.components.RoundedButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(8, 208));
        setResizable(false);

        top.setBackground(new java.awt.Color(255, 255, 255));
        top.setPreferredSize(new java.awt.Dimension(0, 100));
        top.setLayout(new java.awt.GridBagLayout());

        roundedPanel1.setBackground(new java.awt.Color(0, 0, 102));
        roundedPanel1.setRoundBottomLeft(20);
        roundedPanel1.setRoundBottomRight(20);
        roundedPanel1.setRoundTopLeft(20);
        roundedPanel1.setRoundTopRight(20);
        roundedPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Detalles Nota de Entrega");
        roundedPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 500;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        top.add(roundedPanel1, gridBagConstraints);

        getContentPane().add(top, java.awt.BorderLayout.PAGE_START);

        table.setBackground(new java.awt.Color(255, 255, 255));
        table.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(750, 450));

        TableDetalleNotaEntrega.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "ESTE", "ESTE", "ESTE"
            }
        ));
        TableDetalleNotaEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TableDetalleNotaEntrega.setPreferredSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setViewportView(TableDetalleNotaEntrega);

        table.add(jScrollPane1, new java.awt.GridBagConstraints());

        getContentPane().add(table, java.awt.BorderLayout.CENTER);

        buttom.setBackground(new java.awt.Color(255, 255, 255));
        buttom.setPreferredSize(new java.awt.Dimension(100, 100));
        buttom.setLayout(new java.awt.GridBagLayout());

        roundedButton1.setBackground(new java.awt.Color(0, 0, 102));
        roundedButton1.setBorder(null);
        roundedButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-imprimir-60.png"))); // NOI18N
        roundedButton1.setText("");
        roundedButton1.setPreferredSize(new java.awt.Dimension(70, 70));
        roundedButton1.setRoundBottomLeft(20);
        roundedButton1.setRoundBottomRight(20);
        roundedButton1.setRoundTopLeft(20);
        roundedButton1.setRoundTopRight(20);
        roundedButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundedButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 50, 0);
        buttom.add(roundedButton1, gridBagConstraints);

        getContentPane().add(buttom, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roundedButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundedButton1ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "¿Deseas guardar el reporte de nota entrega en pdf?", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setDialogTitle("Seleccione la ubicación para guardar el reporte de nota de entrega");
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            fileChooser.setSelectedFile(new File("reporte de nota.pdf"));
            int userSelection = fileChooser.showSaveDialog(null);
            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File archivoSeleccionado = fileChooser.getSelectedFile();
                try {
                    SistemaPrincipal.getDetalleFacturaService().reporteDetalleFacturasPDF(archivoSeleccionado.getAbsolutePath(), factura.getIdFactura());
                    JOptionPane.showMessageDialog(null, "Reporte de Nota guardado exitosamente en: " + archivoSeleccionado.getAbsolutePath());
                    this.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al generar el reporte de Nota: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "El guardado del reporte de la nota de entrega fue cancelado.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El reporte de nota de entrega no será guardado.");
        }
    }//GEN-LAST:event_roundedButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.luisjuarez.sistemavu.view.components.CustomTable TableDetalleNotaEntrega;
    private javax.swing.JPanel buttom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.luisjuarez.sistemavu.view.components.RoundedButton roundedButton1;
    private com.luisjuarez.sistemavu.view.components.RoundedPanel roundedPanel1;
    private javax.swing.JPanel table;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
